### ISSUE TITLE
Do you still test building on Windows?

### ISSUE THREAD

**Issue by chadchoi** [RolandHughes/ls-cs#19]
I'm building ls-cs using MinGW-w64 (via MSYS2). I can't afford using MSVC. It's too bloated for my outdated legacy Windows installation. You said support for MinGW-w64 is dropped, but I don't see anything specific about MinGW-w64 being removed from the code base, so I expect it to build just fine like the original CopperSpice. But it's not the case. It's failing at `FAILED: src/gui/CMakeFiles/LsCsGui.dir/styles/qwindows_xpstyle.cpp.obj` because `LSCS_ACTIVE`, `LSCS_INACTIVE`, and `LSCS_DISABLED` are undefined. I do a quick grep on the source code and I can't find where they are defined either. I think it will also fail to build with MSVC because it's a coding error. Please correct me if I'm wrong. Thank you.

**Comment by RolandHughes** [comment]
Short answer is No.

There is a long drawn out discussion with another user wanting MinGW/MSYS2 support where I told them I wouldn't support it.

When we get to Windows it will be Native Windows, not a hodge-podge. Haven't had time to check out the compilers in [this article](https://learncplusplus.org/top-c-compilers-for-windows-in-2020/) where they keep trying to push the Embarcadero  IDE.

If you wish to have this run on Windows 7 or any Windows platform, please dig into the free stuff on that list. I was thinking about CLANG, but just don't have time. Windows is a low priority for me. After multiple root canals without pain killers low. It just doesn't really exist in the embedded systems world. Eventually I will want RedDiamond to run on Windows, but there is _so_ much to do before that. Until Servo replaces Webkit, I don't want to think about it.

This is actually a CopperSpice bug so they must not be testing on Windows anymore either.

![bK25wYOK2q4xCjql](https://github.com/user-attachments/assets/f13ca6a5-941a-4d75-a22b-43f8f8a4d46f)

Someone merged a half-done change. I cloned from tip into junk and ran that search.

**CREATE A BRANCH** using the next version number (final digit) 
#define those two constants in src/core/global/qglobal.h

test your build

**DO NOT MERGE**

Once you have successfully built for an unsupported environment, build with one of the native Windows compilers. My preference would be CLANG only because we could switch the Linux build to use that rather easily.

_NOTE:_ CLANG is a much more template restrictive compiler. Qt itself fails to build with CLANG if anyone changes the containers to use constexpr.

**AFTER** it successfully builds _NATIVE_ on Windows and you have the example programs that run on Linux also running native on Windows, let me know and we will look at merging.

I just got back online after having done some room painting and floor refinishing. After I get my Xmas letter written I will finish working on updating CUPS API. I'm about 2/3rds done. Other than having to resolve a version number (assuming you get done before me) we shouldn't have any conflicts. CUPS doesn't generally exist on Windows.

**Comment by mh466lfa** [comment]
Relying on an old and outdated article from 2020 is not a good idea. There are currently two LLVM ports on Windows. One is LLVM-MSVC, that will need Visual Studio installed to work. One is LLVM-MINGW, that is self-contained and you don't need to install anything to make it work. Embarcadero C++ is a poor choice for C++ standard conformant. And as I know, the modern Embarcadero C++ is just a fork of an outdated LLVM Clang. The GCC section in that article is basically what I have always suggested to you, MinGW-w64. I have to emphasize it again. MinGW-w64 is native, native in the same sense as MSVC is native. It doesn't need any emulation layers to work. You are always confusing it with the Cygwin GCC.

**Comment by mh466lfa** [comment]
Btw, CopperSpice has never supported Embarcadero C++ as I know. It has solid support for MinGW-w64, though. They even have their own MinGW-w64 distro (https://github.com/copperspice/cs_mingw_w64).

**Comment by mh466lfa** [comment]
> This is actually a CopperSpice bug so they must not be testing on Windows anymore either.
> 
> ![bK25wYOK2q4xCjql](https://private-user-images.githubusercontent.com/1883220/389611246-f13ca6a5-941a-4d75-a22b-43f8f8a4d46f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2MDY2NzEsIm5iZiI6MTczMjYwNjM3MSwicGF0aCI6Ii8xODgzMjIwLzM4OTYxMTI0Ni1mMTNjYTZhNS05NDFhLTRkNzUtYTIyYi00M2Y4ZjhhNGQ0NmYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjZUMDczMjUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTZhMjhlYWUzZjRkODhlMTRhODcyMDk2Y2EzM2NlMTZjYTljODczMTIxNWFlMzkxZjMwZGNkY2YwYjEyOGIyMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.CqfLyb1PQK5_w_5q7FmRixxSkQ14ineilV1by2Kke7k)
> 
> Someone merged a half-done change. I cloned from tip into junk and ran that search.

Don't blame the CopperSpice people. The latest CopperSpice is still building fine with MinGW-w64 (MSYS2 UCRT64) on Windows.

**Comment by RolandHughes** [comment]
> > This is actually a CopperSpice bug so they must not be testing on Windows anymore either.
> > ![bK25wYOK2q4xCjql](https://private-user-images.githubusercontent.com/1883220/389611246-f13ca6a5-941a-4d75-a22b-43f8f8a4d46f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI2MDY2NzEsIm5iZiI6MTczMjYwNjM3MSwicGF0aCI6Ii8xODgzMjIwLzM4OTYxMTI0Ni1mMTNjYTZhNS05NDFhLTRkNzUtYTIyYi00M2Y4ZjhhNGQ0NmYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjZUMDczMjUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YTZhMjhlYWUzZjRkODhlMTRhODcyMDk2Y2EzM2NlMTZjYTljODczMTIxNWFlMzkxZjMwZGNkY2YwYjEyOGIyMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.CqfLyb1PQK5_w_5q7FmRixxSkQ14ineilV1by2Kke7k)
> > Someone merged a half-done change. I cloned from tip into junk and ran that search.
> 
> Don't blame the CopperSpice people. The latest CopperSpice is still building fine with MinGW-w64 (MSYS2 UCRT64) on Windows.

Take a look at the search. They don't define it either. In order for the current code at tip of the repo to build as you claim, they have to have hacked MinGW-w64.

**Comment by RolandHughes** [comment]
> Relying on an old and outdated article from 2020 is not a good idea. There are currently two LLVM ports on Windows. One is LLVM-MSVC, that will need Visual Studio installed to work. One is LLVM-MINGW, that is self-contained and you don't need to install anything to make it work. Embarcadero C++ is a poor choice for C++ standard conformant. And as I know, the modern Embarcadero C++ is just a fork of an outdated LLVM Clang. The GCC section in that article is basically what I have always suggested to you, MinGW-w64. I have to emphasize it again. MinGW-w64 is native, native in the same sense as MSVC is native. It doesn't need any emulation layers to work. You are always confusing it with the Cygwin GCC.

I'm not relying on an outdated article. I'm being badgered about supporting Windows, a platform that simply doesn't exist in the market for which this is targeted using a "tool" that is just a hack.

If and when I/this project, gets around to supporting Windows it will be with a NATIVE build. No MinGW anything.

Feel free to create your own project and cease wasting my time. You've obviously only scanned, not actually read and comprehended both the manifesto and roadmap.

**This application framework is targeting embedded systems/medical devices and the desktops used to create them.**

Windows doesn't exist in this universe.

What you really don't understand is that MinGW is itself an emulation layer.

This project will not be looking at running on Windows until **__AFTER__ Webkit is replaced by Servo**.

If the person actually contributing to this project gets a full native non-MinGW non-Msys2 non-Cygwin build working and wishes to maintain it, after review, I will consider the merge.

You do not add a pointless OS at this stage of a project. There are tens of thousands of lines of code to be done just to get the base functionality into the primary (Ubuntu 20.04) development world and cross compiling for Armv8 with Yocto/Bitbake recipes for OpenEmbedded.

It will be years before Windows support is "needed" and then it will mostly be so RedDiamond can be native compiled and distributed for Windows.
