### ISSUE TITLE
Why Servo?

### ISSUE THREAD

**Issue by chadchoi** [RolandHughes/ls-cs#22]
What do you think about updating to the latest WebKit instead? WebKit is still being maintained. It's still the engine powering Safari.

p/s: Yes, I know you will use the C interface offered by Servo. But I'm just don't think mixing Rust and C++ will be a good idea.

**Comment by RolandHughes** [comment]
Has to be done.

Apple will only care about Apple. There have been historic differences between Webkit in Safari and what is "in the wild." You are mixing C++ (a type safe language) with JavaScript (a non-type safe language) with Webkit. Qt created the tradgedy known as QML trying to bridge that chasm. They failed.

Won't use Chrome libraries because Google spies on everyone. Also, the [Justices Department is about to bust up Google](https://www.msn.com/en-us/money/companies/justice-department-calls-for-breakup-of-google-and-sale-of-chrome/ar-AA1utzoC?ocid=BingNewsSerp). The browser and most likely Android, will be sold off.

[Rust has safe and unsafe](https://doc.rust-lang.org/nomicon/meet-safe-and-unsafe.html).
Rust is much [better at threading](https://developer.okta.com/blog/2022/03/18/programming-security-and-why-rust) than JavaScript.
Rust can use all of the processors (core) in your CPU. It has a load balancing feature that I haven't fully researched. When you create a thread with C++ (or C) it has an affinity to the core of the parent thread. Unless you go deep into the threading API of the platform, if you create 1,000 threads, they all wait in line behind the primary for the core scheduler to give them a turn.

The Unix/Linux thread libraries/APIs were defined when we only had one core.

Legacy support requires they still operate correctly on a single core CPU.

Rust doesn't have to support legacy processors, at least not at that level. 

Servo has lots of 3D graphics support built in. Servo used to also use GLFW though I'm hearing they might have a Rust native graphics library now. At any rate, communicating with the underlying graphics should still support GLFW in some manner.

With JavaScript and third party Webkit, good luck communicating the display.

**Comment by chadchoi** [comment]
Please have a look at sko's answer on this FreeBSD forums thread:

https://forums.freebsd.org/threads/rdevd-a-devd-re-implemented-on-rust.95642/#post-679241

**Comment by chadchoi** [comment]
BTW, let's see what this effort turns out to be like:

https://www.phoronix.com/news/KDAB-Embed-Servo-Qt

You are not the only one want to play with Servo.

**Comment by chadchoi** [comment]
Another BTW, can WebKit be built without JavaScriptCore? It seems you only hate JavaScript.

**Comment by RolandHughes** [comment]
> Please have a look at sko's answer on this FreeBSD forums thread:
> 
> https://forums.freebsd.org/threads/rdevd-a-devd-re-implemented-on-rust.95642/#post-679241
> 
> Also this:
> 
> https://forums.freebsd.org/threads/the-case-for-rust-in-the-base-system.92024/

I read through the first one but didn't go through all of the rants on the second link.

Yes, Rust has a lot of overhead. That's part of growing pains. The context switch problem is actually a problem with the OS, not Rust. The problem is GUI DOS (Windows) and Linux (even Mac/FreeBSD) started with single core computers. The threading libraries are hamstrung by need for backward compatibility with that ancient code base. 

Rust doesn't have the thread affinity problem, but the OS do a zillion context switches trying to copy data. It's a lot deeper into a hardware/firmware/OS dive discussion than I wish to go, but . . . you can kind-of get some idea reading this discussion about the z820 design.

https://www.techpowerup.com/forums/threads/16-core-32-thread-hp-z820-workstation-build.264743/

On a hardware level the dual CPU mobo has one CPU dominant for certain slots and memory modules. The thing has multiple power rails too. Depending on your OS, if you launch a thread and move it to a core in the different CPU, you can cause a flurry of activity as memory gets copied between regions "owned" by each CPU.

Same thing can happen with moving between core within the same CPU if the firmware or OS has a bunch of memory protection guardrails in place. Scroll down to "core isolation" in this

https://www.dell.com/support/kbdoc/en-us/000124038/bios-and-operating-system-requirements-to-met-support-secured-core-personal-computing

Unlike [ADA](https://en.wikipedia.org/wiki/Ada_(programming_language)), Rust will be successful. ADA, like Algol, was a language designed by academics for academics and forced unto the world. The only reason it is still around is academics got government regulations demanding it in certain fighter jets and bombers. Algol was thankfully taken to the woods and shot.

Granted there is a bit of marketing hype here.

![image](https://github.com/user-attachments/assets/02abb51b-db41-435b-ae1d-4810e8480517)

but it is the garbage collection issue.

People loved Qt3 with OS/2 because the application framework provided garbage collection. This also causes spastic problems.

https://www.logikalsolutions.com/wordpress/uncategorized/so-you-cant-get-your-qt-models-to-work-with-qml/

QML was a fool's design.

Trying to blend a non-type-safe hack that sits on top of JavaScript with its own run-time with the non-type-safe JavaScript run-time and the C++ run-time and Qt's garbage collection will always create unstable systems. In case you don't read the post

![image](https://github.com/user-attachments/assets/4fe1e2bb-db95-415f-921b-df92b15a6029)

If you try to share something between the colored lanes you are effectively drunk driving across all three lanes. Garbage collection will dynamically destroy something one of the other lanes is still using because it has no way of knowing the thing is still in use in the other lanes.

There were two people I used to throw darts with who initially were trying to make QML a compiled-to-c++-widgets script. That didn't happen. Qtc/KDAB/whoever hacked QML on top of JavaScript because that came with Webkit. I haven't looked at what they are working on now for the "QML compiler." I just know it will end up being a dog's breakfast. They are so far down the JavaScript drain the only thing they could do is "compile to JavaScript."

Most of the people whining and sniveling about Rust have never worked with an RTOS. (Real-Time Operating System). There is no dynamic memory allocation. You have to request memory blocks at load time then parcel them out in your application. 

_**Every instruction takes the exact same amount of time no matter what is going on.**_

You cannot be blocked by garbage collection or network access or memory allocation.

https://www.freertos.org/

**Comment by RolandHughes** [comment]
>BTW, let's see what this effort turns out to be like:
>
>https://www.phoronix.com/news/KDAB-Embed-Servo-Qt

No, we will do it first and we will do it right. They are hamstrung by a litany of bad decisions. You can bet it will be viciously coupled with QML. 

There are a few other people chatting with me about this project. Some are very good developers. I'm hoping that with the Servo support we can also remove the single-thread-y-ness which has plagued Qt from day one. Ditch the "main event loop" and become a more immediate mode GUI.

https://en.wikipedia.org/wiki/Immediate_mode_(computer_graphics)

For a nice, lightweight, immediate mode GUI look at [NanoGUI](https://github.com/mitsuba-renderer/nanogui). I mentioned this in either the manifesto or the roadmap. It's one of the main reasons I chose GLFW. 

This will require some long hours of thought and white boarding because "Application Framework" will have to be split between GUI and Application. They will need to be independent with callback communications.

I still hold out hope that one of the guys from NanoGUI project will join this project around the Servo move timeframe. 

Architecturally; in the back of my mind; I think there will be a "software watchdog" for the "main" which launches GUI-thread and Application-thread tied to potentially different cores. The two threads will have callbacks to indicate orderly exit and the watchdog will periodically thump each thread for a heartbeat.

At this point, assuming this project can achieve that, we get rid of the drunk driving problem because any "shared data" will be owned by the watchdog which can keep track of who is still using it prior to nuking.

The C Wrapper stuff for Rust isn't quite good enough.
https://parallel-rust-cpp.github.io/cpp_abi.html

Some academic fool will try to use "smart pointers." 

This is long way out though. Solves a boatload of problems though. 

Currently, I believe it is QCoreApplication that is keeping track of everything but it is in the main thread with the GUI where all graphics have to be rendered. GLFW doesn't care what thread. At least it didn't seem to when I was using NanoGUI for an embedded project.

Maybe I'll get around to updating the RoadMap today?

**Comment by RolandHughes** [comment]
> Another BTW, It seems you only hate JavaScript. Is the removal of LsCsScript is already enough to get rid of JavaScript? Or the whole LsCsWebKit need to be nuked? Can WebKit be built without JavaScriptCore?

Look at the directory tree

`roland@roland-HP-Z820-Workstation:~/github_projects/ls-cs$ find -iname webkit*
./src/webkit
./src/3rdparty/webkit
./src/3rdparty/webkit/include/WebKit2
./src/3rdparty/webkit/WebKitLibraries
./src/3rdparty/webkit/WebKitLibraries/win/include/WebKitSystemInterface
./src/3rdparty/webkit/WebKitLibraries/win/include/WebKitSystemInterface/WebKitSystemInterface.h
./src/3rdparty/webkit/WebKitLibraries/WebKitSystemInterface.h
./src/3rdparty/webkit/Source/WebKit2
./src/3rdparty/webkit/Source/WebKit2/WebKit2Prefix.h
./src/3rdparty/webkit/Source/WebKit2/win/WebKit2WebProcess.resources
./src/3rdparty/webkit/Source/WebKit2/win/WebKit2WebProcessProduction.vsprops
./src/3rdparty/webkit/Source/WebKit2/win/WebKitPreBuild.cmd
./src/3rdparty/webkit/Source/WebKit2/win/WebKit2GeneratedCommon.vsprops
./src/3rdparty/webkit/Source/WebKit2/win/WebKit2WebProcessDebugAll.vsprops
./src/3rdparty/webkit/Source/WebKit2/win/WebKit2WebProcessPostBuild.cmd
./src/3rdparty/webkit/Source/WebKit2/win/WebKit2Generated.make
./src/3rdparty/webkit/Source/WebKit2/win/WebKit2ReleaseCairoCFLite.vsprops
./src/3rdparty/webkit/Source/WebKit2/win/WebKit2.def
./src/3rdparty/webkit/Source/WebKit2/win/WebKit2Common.vsprops
./src/3rdparty/webkit/Source/WebKit2/win/WebKit2.make
./src/3rdparty/webkit/Source/WebKit2/win/WebKit2Debug.vsprops
./src/3rdparty/webkit/Source/WebKit2/win/WebKit2DirectX.vsprops
./src/3rdparty/webkit/Source/WebKit2/win/WebKit2CFLite.vsprops
./src/3rdparty/webkit/Source/WebKit2/win/WebKit2WebProcessReleaseCairoCFLite.vsprops
./src/3rdparty/webkit/Source/WebKit2/win/WebKit2CFLite.def
./src/3rdparty/webkit/Source/WebKit2/win/WebKit2Release.vsprops
./src/3rdparty/webkit/Source/WebKit2/win/WebKit2.rc
./src/3rdparty/webkit/Source/WebKit2/win/WebKit2WebProcessRelease.vsprops
./src/3rdparty/webkit/Source/WebKit2/win/WebKit2Apple.vsprops
./src/3rdparty/webkit/Source/WebKit2/win/WebKit2WebProcessDebug.vsprops
./src/3rdparty/webkit/Source/WebKit2/win/WebKit2Production.vsprops
./src/3rdparty/webkit/Source/WebKit2/win/WebKit2DebugCairoCFLite.vsprops
./src/3rdparty/webkit/Source/WebKit2/win/WebKit2WebProcessDebugCairoCFLite.vsprops
./src/3rdparty/webkit/Source/WebKit2/win/WebKitPostBuild.cmd
./src/3rdparty/webkit/Source/WebKit2/win/WebKit2WebProcessPreBuild.cmd
./src/3rdparty/webkit/Source/WebKit2/win/WebKit2DebugAll.vsprops
./src/3rdparty/webkit/Source/WebKit2/win/WebKit2WebProcessCommon.vsprops
./src/3rdparty/webkit/Source/WebKit2/win/WebKitPreLink.cmd
./src/3rdparty/webkit/Source/WebKit2/gtk/webkit2.pc.in
./src/3rdparty/webkit/Source/WebKit2/Shared/win/WebKitBundle.h
./src/3rdparty/webkit/Source/WebKit2/Shared/win/WebKitBundle.cpp
./src/3rdparty/webkit/Source/WebKit2/Configurations/WebKit2.xcconfig
./src/3rdparty/webkit/Source/WebKit2/UIProcess/API/gtk/WebKitWebViewBase.h
./src/3rdparty/webkit/Source/WebKit2/UIProcess/API/gtk/WebKitWebViewBasePrivate.h
./src/3rdparty/webkit/Source/WebKit2/UIProcess/API/gtk/WebKitWebViewBase.cpp
./src/3rdparty/webkit/Source/WebKit2/UIProcess/API/C/WebKit2.h
./src/3rdparty/webkit/Source/WebKit2/WebKit2Prefix.cpp
./src/3rdparty/webkit/Source/WebKit2/WebProcess/WebKitMain.cpp
./src/3rdparty/webkit/Source/WebKit2/Scripts/webkit2
./src/3rdparty/webkit/Source/JavaScriptCore/API/WebKitAvailability.h
./src/3rdparty/webkit/Source/JavaScriptCore/ForwardingHeaders/JavaScriptCore/WebKitAvailability.h
./src/3rdparty/webkit/Source/WebCore/generated/WebKitVersion.h
./src/3rdparty/webkit/Source/WebCore/bindings/gobject/WebKitHTMLElementWrapperFactory.h
./src/3rdparty/webkit/Source/WebCore/bindings/gobject/WebKitDOMObject.h
./src/3rdparty/webkit/Source/WebCore/bindings/gobject/WebKitDOMObject.cpp
./src/3rdparty/webkit/Source/WebCore/bindings/gobject/WebKitDOMBinding.cpp
./src/3rdparty/webkit/Source/WebCore/bindings/gobject/WebKitDOMBinding.h
./src/3rdparty/webkit/Source/WebCore/bindings/gobject/WebKitDOMEventTarget.cpp
./src/3rdparty/webkit/Source/WebCore/bindings/gobject/WebKitDOMEventTarget.h
./src/3rdparty/webkit/Source/WebCore/bindings/gobject/WebKitHTMLElementWrapperFactory.cpp
./src/3rdparty/webkit/Source/WebCore/bindings/gobject/WebKitDOMEventTargetPrivate.h
./src/3rdparty/webkit/Source/WebCore/bindings/scripts/test/GObject/WebKitDOMTestMediaQueryListListener.h
./src/3rdparty/webkit/Source/WebCore/bindings/scripts/test/GObject/WebKitDOMTestInterfacePrivate.h
./src/3rdparty/webkit/Source/WebCore/bindings/scripts/test/GObject/WebKitDOMTestCallbackPrivate.h
./src/3rdparty/webkit/Source/WebCore/bindings/scripts/test/GObject/WebKitDOMTestObj.h
./src/3rdparty/webkit/Source/WebCore/bindings/scripts/test/GObject/WebKitDOMTestSerializedScriptValueInterfacePrivate.h
./src/3rdparty/webkit/Source/WebCore/bindings/scripts/test/GObject/WebKitDOMTestSerializedScriptValueInterface.cpp
./src/3rdparty/webkit/Source/WebCore/bindings/scripts/test/GObject/WebKitDOMTestCallback.h
./src/3rdparty/webkit/Source/WebCore/bindings/scripts/test/GObject/WebKitDOMTestCallback.cpp
./src/3rdparty/webkit/Source/WebCore/bindings/scripts/test/GObject/WebKitDOMTestMediaQueryListListenerPrivate.h
./src/3rdparty/webkit/Source/WebCore/bindings/scripts/test/GObject/WebKitDOMTestSerializedScriptValueInterface.h
./src/3rdparty/webkit/Source/WebCore/bindings/scripts/test/GObject/WebKitDOMTestObjPrivate.h
./src/3rdparty/webkit/Source/WebCore/bindings/scripts/test/GObject/WebKitDOMTestObj.cpp
./src/3rdparty/webkit/Source/WebCore/bindings/scripts/test/GObject/WebKitDOMTestInterface.cpp
./src/3rdparty/webkit/Source/WebCore/bindings/scripts/test/GObject/WebKitDOMTestMediaQueryListListener.cpp
./src/3rdparty/webkit/Source/WebCore/bindings/scripts/test/GObject/WebKitDOMTestInterface.h
./src/3rdparty/webkit/Source/WebCore/fileapi/WebKitBlobBuilder.h
./src/3rdparty/webkit/Source/WebCore/fileapi/WebKitBlobBuilder.cpp
./src/3rdparty/webkit/Source/WebCore/fileapi/WebKitFlags.idl
./src/3rdparty/webkit/Source/WebCore/fileapi/WebKitBlobBuilder.idl
./src/3rdparty/webkit/Source/WebCore/fileapi/WebKitFlags.h
./src/3rdparty/webkit/Source/WebCore/dom/WebKitAnimationEvent.cpp
./src/3rdparty/webkit/Source/WebCore/dom/WebKitAnimationEvent.h
./src/3rdparty/webkit/Source/WebCore/dom/WebKitTransitionEvent.cpp
./src/3rdparty/webkit/Source/WebCore/dom/WebKitTransitionEvent.idl
./src/3rdparty/webkit/Source/WebCore/dom/WebKitTransitionEvent.h
./src/3rdparty/webkit/Source/WebCore/dom/WebKitAnimationEvent.idl
./src/3rdparty/webkit/Source/WebCore/page/WebKitAnimation.idl
./src/3rdparty/webkit/Source/WebCore/page/WebKitAnimation.cpp
./src/3rdparty/webkit/Source/WebCore/page/WebKitAnimationList.cpp
./src/3rdparty/webkit/Source/WebCore/page/WebKitAnimation.h
./src/3rdparty/webkit/Source/WebCore/page/WebKitAnimationList.h
./src/3rdparty/webkit/Source/WebCore/page/WebKitAnimationList.idl
./src/3rdparty/webkit/Source/WebCore/page/WebKitPoint.h
./src/3rdparty/webkit/Source/WebCore/page/WebKitPoint.idl
./src/3rdparty/webkit/Source/WebCore/inspector/front-end/WebKit.qrc
./src/3rdparty/webkit/Source/WebCore/platform/graphics/gstreamer/WebKitWebSourceGStreamer.h
./src/3rdparty/webkit/Source/WebCore/platform/graphics/gstreamer/WebKitWebSourceGStreamer.cpp
./src/3rdparty/webkit/Source/WebCore/html/canvas/WebKitLoseContext.h
./src/3rdparty/webkit/Source/WebCore/html/canvas/WebKitLoseContext.cpp
./src/3rdparty/webkit/Source/WebCore/html/canvas/WebKitLoseContext.idl
./src/3rdparty/webkit/Source/WebCore/css/WebKitCSSKeyframeRule.idl
./src/3rdparty/webkit/Source/WebCore/css/WebKitCSSKeyframeRule.cpp
./src/3rdparty/webkit/Source/WebCore/css/WebKitCSSTransformValue.h
./src/3rdparty/webkit/Source/WebCore/css/WebKitCSSMatrix.idl
./src/3rdparty/webkit/Source/WebCore/css/WebKitCSSKeyframesRule.h
./src/3rdparty/webkit/Source/WebCore/css/WebKitCSSKeyframeRule.h
./src/3rdparty/webkit/Source/WebCore/css/WebKitCSSMatrix.h
./src/3rdparty/webkit/Source/WebCore/css/WebKitCSSKeyframesRule.cpp
./src/3rdparty/webkit/Source/WebCore/css/WebKitCSSKeyframesRule.idl
./src/3rdparty/webkit/Source/WebCore/css/WebKitCSSMatrix.cpp
./src/3rdparty/webkit/Source/WebCore/css/WebKitCSSTransformValue.cpp
./src/3rdparty/webkit/Source/WebCore/css/WebKitCSSTransformValue.idl
./src/3rdparty/webkit/Source/WebKit
./src/3rdparty/javascriptcore/JavaScriptCore/API/WebKitAvailability.h
./src/3rdparty/javascriptcore/JavaScriptCore/ForwardingHeaders/JavaScriptCore/WebKitAvailability.h
roland@roland-HP-Z820-Workstation:~/github_projects/ls-cs$
`

Remember the focus.

1. Use external platform available packages/libraries for most functionality
2. Eliminate single-thread-y-ness as much as possible.
3. FDA 510K verifiable.

I will update the roadmap, but we are a long way from getting the GLFW stuff done because several other classes have to be created first, notably Serial and Digital I/O.

**Comment by chadchoi** [comment]
> > Another BTW, It seems you only hate JavaScript. Is the removal of LsCsScript is already enough to get rid of JavaScript? Or the whole LsCsWebKit need to be nuked? Can WebKit be built without JavaScriptCore?
> 
> Look at the directory tree
> 
> `roland@roland-HP-Z820-Workstation:~/github_projects/ls-cs$ find -iname webkit* ./src/webkit ./src/3rdparty/webkit ./src/3rdparty/webkit/include/WebKit2 ./src/3rdparty/webkit/WebKitLibraries ./src/3rdparty/webkit/WebKitLibraries/win/include/WebKitSystemInterface ./src/3rdparty/webkit/WebKitLibraries/win/include/WebKitSystemInterface/WebKitSystemInterface.h ./src/3rdparty/webkit/WebKitLibraries/WebKitSystemInterface.h ./src/3rdparty/webkit/Source/WebKit2 ./src/3rdparty/webkit/Source/WebKit2/WebKit2Prefix.h ./src/3rdparty/webkit/Source/WebKit2/win/WebKit2WebProcess.resources ./src/3rdparty/webkit/Source/WebKit2/win/WebKit2WebProcessProduction.vsprops ./src/3rdparty/webkit/Source/WebKit2/win/WebKitPreBuild.cmd ./src/3rdparty/webkit/Source/WebKit2/win/WebKit2GeneratedCommon.vsprops ./src/3rdparty/webkit/Source/WebKit2/win/WebKit2WebProcessDebugAll.vsprops ./src/3rdparty/webkit/Source/WebKit2/win/WebKit2WebProcessPostBuild.cmd ./src/3rdparty/webkit/Source/WebKit2/win/WebKit2Generated.make ./src/3rdparty/webkit/Source/WebKit2/win/WebKit2ReleaseCairoCFLite.vsprops ./src/3rdparty/webkit/Source/WebKit2/win/WebKit2.def ./src/3rdparty/webkit/Source/WebKit2/win/WebKit2Common.vsprops ./src/3rdparty/webkit/Source/WebKit2/win/WebKit2.make ./src/3rdparty/webkit/Source/WebKit2/win/WebKit2Debug.vsprops ./src/3rdparty/webkit/Source/WebKit2/win/WebKit2DirectX.vsprops ./src/3rdparty/webkit/Source/WebKit2/win/WebKit2CFLite.vsprops ./src/3rdparty/webkit/Source/WebKit2/win/WebKit2WebProcessReleaseCairoCFLite.vsprops ./src/3rdparty/webkit/Source/WebKit2/win/WebKit2CFLite.def ./src/3rdparty/webkit/Source/WebKit2/win/WebKit2Release.vsprops ./src/3rdparty/webkit/Source/WebKit2/win/WebKit2.rc ./src/3rdparty/webkit/Source/WebKit2/win/WebKit2WebProcessRelease.vsprops ./src/3rdparty/webkit/Source/WebKit2/win/WebKit2Apple.vsprops ./src/3rdparty/webkit/Source/WebKit2/win/WebKit2WebProcessDebug.vsprops ./src/3rdparty/webkit/Source/WebKit2/win/WebKit2Production.vsprops ./src/3rdparty/webkit/Source/WebKit2/win/WebKit2DebugCairoCFLite.vsprops ./src/3rdparty/webkit/Source/WebKit2/win/WebKit2WebProcessDebugCairoCFLite.vsprops ./src/3rdparty/webkit/Source/WebKit2/win/WebKitPostBuild.cmd ./src/3rdparty/webkit/Source/WebKit2/win/WebKit2WebProcessPreBuild.cmd ./src/3rdparty/webkit/Source/WebKit2/win/WebKit2DebugAll.vsprops ./src/3rdparty/webkit/Source/WebKit2/win/WebKit2WebProcessCommon.vsprops ./src/3rdparty/webkit/Source/WebKit2/win/WebKitPreLink.cmd ./src/3rdparty/webkit/Source/WebKit2/gtk/webkit2.pc.in ./src/3rdparty/webkit/Source/WebKit2/Shared/win/WebKitBundle.h ./src/3rdparty/webkit/Source/WebKit2/Shared/win/WebKitBundle.cpp ./src/3rdparty/webkit/Source/WebKit2/Configurations/WebKit2.xcconfig ./src/3rdparty/webkit/Source/WebKit2/UIProcess/API/gtk/WebKitWebViewBase.h ./src/3rdparty/webkit/Source/WebKit2/UIProcess/API/gtk/WebKitWebViewBasePrivate.h ./src/3rdparty/webkit/Source/WebKit2/UIProcess/API/gtk/WebKitWebViewBase.cpp ./src/3rdparty/webkit/Source/WebKit2/UIProcess/API/C/WebKit2.h ./src/3rdparty/webkit/Source/WebKit2/WebKit2Prefix.cpp ./src/3rdparty/webkit/Source/WebKit2/WebProcess/WebKitMain.cpp ./src/3rdparty/webkit/Source/WebKit2/Scripts/webkit2 ./src/3rdparty/webkit/Source/JavaScriptCore/API/WebKitAvailability.h ./src/3rdparty/webkit/Source/JavaScriptCore/ForwardingHeaders/JavaScriptCore/WebKitAvailability.h ./src/3rdparty/webkit/Source/WebCore/generated/WebKitVersion.h ./src/3rdparty/webkit/Source/WebCore/bindings/gobject/WebKitHTMLElementWrapperFactory.h ./src/3rdparty/webkit/Source/WebCore/bindings/gobject/WebKitDOMObject.h ./src/3rdparty/webkit/Source/WebCore/bindings/gobject/WebKitDOMObject.cpp ./src/3rdparty/webkit/Source/WebCore/bindings/gobject/WebKitDOMBinding.cpp ./src/3rdparty/webkit/Source/WebCore/bindings/gobject/WebKitDOMBinding.h ./src/3rdparty/webkit/Source/WebCore/bindings/gobject/WebKitDOMEventTarget.cpp ./src/3rdparty/webkit/Source/WebCore/bindings/gobject/WebKitDOMEventTarget.h ./src/3rdparty/webkit/Source/WebCore/bindings/gobject/WebKitHTMLElementWrapperFactory.cpp ./src/3rdparty/webkit/Source/WebCore/bindings/gobject/WebKitDOMEventTargetPrivate.h ./src/3rdparty/webkit/Source/WebCore/bindings/scripts/test/GObject/WebKitDOMTestMediaQueryListListener.h ./src/3rdparty/webkit/Source/WebCore/bindings/scripts/test/GObject/WebKitDOMTestInterfacePrivate.h ./src/3rdparty/webkit/Source/WebCore/bindings/scripts/test/GObject/WebKitDOMTestCallbackPrivate.h ./src/3rdparty/webkit/Source/WebCore/bindings/scripts/test/GObject/WebKitDOMTestObj.h ./src/3rdparty/webkit/Source/WebCore/bindings/scripts/test/GObject/WebKitDOMTestSerializedScriptValueInterfacePrivate.h ./src/3rdparty/webkit/Source/WebCore/bindings/scripts/test/GObject/WebKitDOMTestSerializedScriptValueInterface.cpp ./src/3rdparty/webkit/Source/WebCore/bindings/scripts/test/GObject/WebKitDOMTestCallback.h ./src/3rdparty/webkit/Source/WebCore/bindings/scripts/test/GObject/WebKitDOMTestCallback.cpp ./src/3rdparty/webkit/Source/WebCore/bindings/scripts/test/GObject/WebKitDOMTestMediaQueryListListenerPrivate.h ./src/3rdparty/webkit/Source/WebCore/bindings/scripts/test/GObject/WebKitDOMTestSerializedScriptValueInterface.h ./src/3rdparty/webkit/Source/WebCore/bindings/scripts/test/GObject/WebKitDOMTestObjPrivate.h ./src/3rdparty/webkit/Source/WebCore/bindings/scripts/test/GObject/WebKitDOMTestObj.cpp ./src/3rdparty/webkit/Source/WebCore/bindings/scripts/test/GObject/WebKitDOMTestInterface.cpp ./src/3rdparty/webkit/Source/WebCore/bindings/scripts/test/GObject/WebKitDOMTestMediaQueryListListener.cpp ./src/3rdparty/webkit/Source/WebCore/bindings/scripts/test/GObject/WebKitDOMTestInterface.h ./src/3rdparty/webkit/Source/WebCore/fileapi/WebKitBlobBuilder.h ./src/3rdparty/webkit/Source/WebCore/fileapi/WebKitBlobBuilder.cpp ./src/3rdparty/webkit/Source/WebCore/fileapi/WebKitFlags.idl ./src/3rdparty/webkit/Source/WebCore/fileapi/WebKitBlobBuilder.idl ./src/3rdparty/webkit/Source/WebCore/fileapi/WebKitFlags.h ./src/3rdparty/webkit/Source/WebCore/dom/WebKitAnimationEvent.cpp ./src/3rdparty/webkit/Source/WebCore/dom/WebKitAnimationEvent.h ./src/3rdparty/webkit/Source/WebCore/dom/WebKitTransitionEvent.cpp ./src/3rdparty/webkit/Source/WebCore/dom/WebKitTransitionEvent.idl ./src/3rdparty/webkit/Source/WebCore/dom/WebKitTransitionEvent.h ./src/3rdparty/webkit/Source/WebCore/dom/WebKitAnimationEvent.idl ./src/3rdparty/webkit/Source/WebCore/page/WebKitAnimation.idl ./src/3rdparty/webkit/Source/WebCore/page/WebKitAnimation.cpp ./src/3rdparty/webkit/Source/WebCore/page/WebKitAnimationList.cpp ./src/3rdparty/webkit/Source/WebCore/page/WebKitAnimation.h ./src/3rdparty/webkit/Source/WebCore/page/WebKitAnimationList.h ./src/3rdparty/webkit/Source/WebCore/page/WebKitAnimationList.idl ./src/3rdparty/webkit/Source/WebCore/page/WebKitPoint.h ./src/3rdparty/webkit/Source/WebCore/page/WebKitPoint.idl ./src/3rdparty/webkit/Source/WebCore/inspector/front-end/WebKit.qrc ./src/3rdparty/webkit/Source/WebCore/platform/graphics/gstreamer/WebKitWebSourceGStreamer.h ./src/3rdparty/webkit/Source/WebCore/platform/graphics/gstreamer/WebKitWebSourceGStreamer.cpp ./src/3rdparty/webkit/Source/WebCore/html/canvas/WebKitLoseContext.h ./src/3rdparty/webkit/Source/WebCore/html/canvas/WebKitLoseContext.cpp ./src/3rdparty/webkit/Source/WebCore/html/canvas/WebKitLoseContext.idl ./src/3rdparty/webkit/Source/WebCore/css/WebKitCSSKeyframeRule.idl ./src/3rdparty/webkit/Source/WebCore/css/WebKitCSSKeyframeRule.cpp ./src/3rdparty/webkit/Source/WebCore/css/WebKitCSSTransformValue.h ./src/3rdparty/webkit/Source/WebCore/css/WebKitCSSMatrix.idl ./src/3rdparty/webkit/Source/WebCore/css/WebKitCSSKeyframesRule.h ./src/3rdparty/webkit/Source/WebCore/css/WebKitCSSKeyframeRule.h ./src/3rdparty/webkit/Source/WebCore/css/WebKitCSSMatrix.h ./src/3rdparty/webkit/Source/WebCore/css/WebKitCSSKeyframesRule.cpp ./src/3rdparty/webkit/Source/WebCore/css/WebKitCSSKeyframesRule.idl ./src/3rdparty/webkit/Source/WebCore/css/WebKitCSSMatrix.cpp ./src/3rdparty/webkit/Source/WebCore/css/WebKitCSSTransformValue.cpp ./src/3rdparty/webkit/Source/WebCore/css/WebKitCSSTransformValue.idl ./src/3rdparty/webkit/Source/WebKit ./src/3rdparty/javascriptcore/JavaScriptCore/API/WebKitAvailability.h ./src/3rdparty/javascriptcore/JavaScriptCore/ForwardingHeaders/JavaScriptCore/WebKitAvailability.h roland@roland-HP-Z820-Workstation:~/github_projects/ls-cs$ `
> 
> Remember the focus.
> 
>     1. Use external platform available packages/libraries for most functionality
> 
>     2. Eliminate single-thread-y-ness as much as possible.
> 
>     3. FDA 510K verifiable.
> 
> 
> I will update the roadmap, but we are a long way from getting the GLFW stuff done because several other classes have to be created first, notably Serial and Digital I/O.

I don't understand what you are wanting me to do. Please elaborate more.
