### ISSUE TITLE
Conflicts with the Official CopperSpice Project

### ISSUE THREAD

**Issue by bgeller** [RolandHughes/ls-cs#6]
You are totally free to pursue a fork of our project and we encourage this endeavor.  We know you have not been happy with Qt or CS and doing you own project is a truly wonderful idea. 

The name you have chosen for your library is too similar to CopperSpice and this is unethical.  We strongly ask you to modify the name so users of your system fully understand you are ***not*** connected to our project. 

You have left our web site URL on your github profile, this is misleading.  We know you are disappointed that CopperSpice is moving to C++20, however publishing disparaging remarks on your project site is both inappropriate and unprofessional.  

You github readme file should be modified to remove all references to the CopperSpice project, our published C++ videos, links to the CopperSpice documentation, and information about our other libraries like CsLibguarded, CsString, and CsSignal. 

We wish you the best and hope the conflicts we have mentioned can be resolved amicably.  

Barbara Geller
Co-Founder CopperSpice Project

**Comment by agserm** [comment]
I have a few comments. In addition to the items already mentioned in this issue,  you need to change every library name so they do not conflict with CsCore, CsGui, etc. Also, remember to change the names of the exported CMake modules. 

As I am sure you are aware you must maintain the copyright notice on every  source file. Of course you can add your name at the top if you wish. For obvious reasons you must use the exact license of LGPL 2.1 to distribute your changes.

We need you to make it very clear on this git repository that users of your library should contact you directly for technical support. 

Ansel

**Comment by mh466lfa** [comment]
@RolandHughes I think you should resolve this branding issue first before attempting to work on anything else. You need to refactor the code to switch to your own branding. I found your current branding is clumsy, too. Instead of LsCs, why can't it simply Ls or Lk? You can clearly see whether if `LsCsCore` or `LsCore`/`LkCore` is better.

**Comment by RolandHughes** [comment]
All of the current changes are in https://github.com/RolandHughes/ls-cs/tree/ls-cs-0.1.0. They have not yet been merged into Master because I am not done. **I didn't announce this** on social media because it is not done. One person who owns some of my books and does some embedded systems work found out about it and then announced it on some social media site. I know they meant well, but until something can be properly packaged it shouldn't be announced.

The name will remain LsCs until it is done. Right now it is not done and until harvest is over my time is short. Once harvest is over I can push full tilt on LsCs.

When it gets to the end of [this roadmap](https://lscs-software.com/LsCs-Roadmap.html), it will be "done." At that point those using it and participating in it can choose a new name. At that point it will be what both Qt and CopperSpice should have been. It's already drawing a lot of interest from medical device developers.

I will merge the 010 branch when I have the Arm64 package building and at least two examples running on the Toradex Armv8 Verdin system. Went down a bit of a needless rabbit hole with Multi-Arch Debian packaging.

When the person went onto social media GitHub hadn't even split this thing off, it was still a fork. It wasn't officially separated until yesterday morning. If you look at that branch you will see something like 80-90% of the branding has been resolved already.

Many names are being kicked around. I'm not renaming again until the roadmap gets all the way down to having DICOM support built in. At that point "the community" will choose a name. Some also want to bring in classes to make surgical robots easier to develop and test. Personally I believe that would be a good addition to whatever the new name is.

>publishing disparaging remarks on your project site is both inappropriate and unprofessional.
Yet everybody asks why one splits to a new project instead of just contributing to an existing one and there is no polite way to answer.

**Comment by bgeller** [comment]
This is not completed but you are of course free to close the ticket. 

I will restate, we are very happy you are doing this project.  We want to avoid confusion in the market place and it is imperative that users know your project is ***not*** associated with CopperSpice and you are separate entity.

Your current README has our website links and our names in bold. This much should be changed right away. Your domain name is infringing on our name as well. CopperSpice is known in the industry as CS.  One of our clients reached out to our team asking about "CS" and I am sure this not what you intended. They were of course very happy to hear your project is simply a fork. 

Barbara

**Comment by RolandHughes** [comment]
Which README? The one in Master or the one in the branch?

I'm only interested to hear about the one in the branch. That is the one which will be merged and placed in that other place GitHub inexcusably wants.

A larger rename will not happen until the end of the roadmap.

**Comment by bgeller** [comment]
The README on master is what people see when they go to your github public repository. You can edit this directly from github and just delete everything but your notice. This one minor change will clear up confusion and be very helpful to the CS team, our clients, and the community.

**Comment by RolandHughes** [comment]
And when I merge it will be done.

Every message I have to respond to on here delays that getting done by a significant amount.

I have a very narrow window of time that I can spend on this until harvest is over. Until I am ready to merge, that "one minor change" isn't getting done.

**Comment by chatchoi** [comment]
I have updated README.md according to the request from CopperSpice. This trivial thing is what I can help.

**Comment by mh466lfa** [comment]
I guess you don't have much experience with Github? Go here and you can see, `master` is the default branch:

https://github.com/RolandHughes/ls-cs/branches

This is the branch people will see when visiting your Github project and this is where spreading confusion. CopperSpice people just don't care about your `ls-cs-0.1.0` branch. It's not default and people will have to manually switch to this branch to view it.

**Comment by RolandHughes** [comment]
It will be the default in a few days. That was my point. They needed to look at the one in the branch so it could just be moved up.

I will be tied up helping with soybean harvest for a few days . . . well . . . today anyway. Then I will be back at it on this. Got the documentation for how to create Arm64 cross compile on Ubuntu platforms almost 3/4 done. Lost more than half a day with this exchange and the other half with Debian. They have two different tools for creating Uboot and Kernel cross compiles, but nada to support a standard cross compilation work flow.

Will be setting it up for both traditional and Docker builds.
