### ISSUE TITLE
Manjaro/Arch Linux build script

### ISSUE THREAD

**Issue by mh466lfa** [RolandHughes/ls-cs#9]
There is a PKGBUILD for CopperSpice on Arch AUR. Could be adapted for LsCs.

**Comment by RolandHughes** [comment]
No it can't!!!

It is something of a train wreck. I tried to use it with RedDiamond on Manjaro. The files don't end up in the correct system locations. I will get around to a PKGBUILD at some point . . . _after_ the GLFW conversion. That will be the cleanest point.

**Comment by mh466lfa** [comment]
Are you talking about this [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=copperspice)?

What are the correct locations that you expect? CopperSpice doesn't support the Linux [FHS](https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard). The Arch AUR packagers have to hack it by installing it into `/usr/lib/copperspice`. It's like you extract CopperSpice's binary release into `/usr/lib/copperspice`. Then they use symlinks to link the binaries in `/usr/lib/copperspice/bin` into `/usr/bin`. The PKGBUILD is pretty straightforward. There is nothing hard to understand here.

**Comment by mh466lfa** [comment]
Based on your answer on the MX Linux thread, it seems you are relying on RPATH so you could install directly into the Linux FHS (/usr directory). I think you could learn something from the way Qt applications are packaged on Linux. CopperSpice isn't the first to come up with the platform plugins idea. It's from Qt. CopperSpice's CMake build scripts emulated the `windeployqt`/`linuxdeployqt` tools of Qt.

**Comment by RolandHughes** [comment]
No. CopperSpice (and Qt) rely on hacking RPATH because they have a poochified distribution tree. I've been in IT roughly 40 years now. Started out on real computers with real operating systems. Even wrote a lot of OS/2 code back in they day. What both Qt and by extension CopperSpice have is a hack of a hack. It came forward from the Windows 3.x and OS/2 days when we had 40 MEG hard drives and no rules.

LsCs (and whatever name it has later) currently does follow FHS and it will continue to do so. This is required to avoid a hack of a hack of a hack in the embedded systems world.

The PKGBUILD in the AUR is a horrible package. I tried to use it for actual CopperSpice work. It will never be the base. I will get to a PKGBUILD when I get to it, but we ain't there yet.

Take a very good look at the few lines of text on [this page](https://lscs-software.com/).

=====
LsCs is a cross platform GUI library forked from CopperSpice focusing on Desktops and Embedded systems.

The primary market will be Medical Devices and those who develop them.

We will not support phones in any way shape or form.

The ultimate goal is to have a free cross platform C++ library that sails through FDA 510k validation.
=====

There is no interest in attempting to be all things to all people. Windows 7 will need some level of native support because there is a lot of it in the medical systems field. That support will need to be native. It may have to be only 64-bit Windows 7. I do not know right now and I do not want to waste time pursuing non-standard things and maintaining failed designs.

**Comment by RolandHughes** [comment]
Platform plugins are something as dated as OS/2. They are one of the reasons the Qt bug database was tipping the scales at north of 30K the other day.
![qt-bugs-20241017](https://github.com/user-attachments/assets/e2dcdc65-26f2-43b6-8b1c-dcfdae14d0d8)

NIH (Not Invented Hear) syndrome leads to a lot of needless issues. There was a time around the end of OS/2 where Qt was everywhere. They could get away with roll-your-own plugins. Now, due to massively excessive licensing fees and a bug database north of 30K
![qt-bugs-20241017](https://github.com/user-attachments/assets/6302f280-bf5b-456e-9920-aad9461e1fd2)
Qt is basically nowhere. Token few companies trapped with it. One of the main reasons they stopped the community from maintaining a Qt 5.x LTS was that nobody had any interest in the Qt 6 bugs or licensing fee structure. As a result, only an extremely tiny subset of developers ran their code. Fixing bugs doesn't sell new license, features do, so the bug database explodes. As part of the 510K process a company has to conduct a formal RISK analysis with actual formal documentation. Convincing the FDA that a product/library having a bug database north of 30K in size, and some bugs old enough to drive in America, maybe some are even old enough to drink now, is a tough sell.

While reported and ignored bugs are unforgivable when you are charging hundreds of thousands of dollars for developer seat, [I had one client pay north of $600K for three (3) developer seats.] the larger fear is "just how many bugs never got both found and reported due to so few developers using the product now?" NIH requires a massive non-automated testing effort to be solid.

You really need to read [the RoadMap](https://lscs-software.com/LsCs-Roadmap.html).  You also need to learn the definition of Legacy. Legacy may survive for a while, but it cannot grow.

Platform plugins are dead branches of a tree that must be pruned so the tree may thrive.

GLFW was _not_ chosen blindly. Unlike Gtk, it is not tied to any desktop that I know of. I use Scintilla in RedDiamond. Scintilla used Gtk for its widget. It's having all kinds of trouble now because Gtk did stuff for Gnome that doesn't work with the Wayland compositors for other desktops. A large part of the Gtk community won't care. GLFW comes basically from the OpenGL community developers. It straddles everything. Vulkan, Wayland, OpenGL ES, etc. Servo was even using it until they found a "pure Rust" thing yet appear to still support GLFW.

Since at least 2011 there have been [instructions for using GLFW in Code::Blocks](https://www.codeincodeblock.com/2011/02/setup-glfw-project-in-codeblock.html) and not too long after that [instructions for Eclipse](https://stackoverflow.com/questions/23190186/setup-eclipse-linker-to-compile-and-run-glfw-applications-how-to).

It is physically impossible to measure the number of applications and developers using it. GLFW took the correct approach. It provides just a graphics layer API to straddle all the major ones. Not beholden to any desktop. There are millions, probably tens of millions, of developers using it. I'm told many of the GLFW contributors are also developers in the various OpenGL projects and those projects communicate directly with NVidia, Radeon, etc. graphics card driver developers.

We can lose thousands of lines of buggy code jettisoning the legacy platform plugins. 

One of the seemingly countless cross platform libraries I've used over my many decade careers was Zinc. Some flavor of that library still exists as [OpenZinc](http://openzinc.com/). It tried to use "native" graphics of each platform (impossible under DOS since it didn't have any) and provide a common set of widgets. It failed because it could only have a Least Common Denominator set of features. They were constantly having to add features to the internal DOS graphics library just to add something that already existed on Windows, OS/2, and Apple.

It needed what we have now with GLFW, a single graphics API supported by all of the platforms they cared about. It's a stable base from whence to build lasting goodness. Definitely millions, probably tens of millions, of developers keeping it solid.

Btw, the reason CopperSpice had to put binaries in a bin dir under the lib was they never changed the names of the binaries. We don't have that problem.

**Comment by RolandHughes** [comment]
Btw, yes, probably the "free" version of the Microsoft compiler, but we also might use [OpenWatcom](https://github.com/open-watcom/open-watcom-v2#open-watcom-v2-fork).

https://github.com/open-watcom/open-watcom-v2/wiki/Build#building-open-watcom

Experiments need to be done with it.

**Comment by mh466lfa** [comment]
> Btw, yes, probably the "free" version of the Microsoft compiler, but we also might use [OpenWatcom](https://github.com/open-watcom/open-watcom-v2#open-watcom-v2-fork).
> 
> https://github.com/open-watcom/open-watcom-v2/wiki/Build#building-open-watcom
> 
> Experiments need to be done with it.

Nonsense. Dictating MSVC to be the only supported compiler on Windows is a least reasonable. But dropping MinGW-w64 for OpenWatcom? OpenWatcom doesn't support generating 64 bit binaries yet, doesn't support any C++ standards (its support for C++ is currently in pre-C++98 state), and is a single-man project with a very hostile developer. The license of it is also problematic. The effort to re-license it into Apache license is still nowhere even though having lasted for many years!

**Comment by RolandHughes** [comment]
I haven't dug into it. You have the cart about 8 miles in front of the horse.

Most of the developers for OpenWatcom used to work for a video card driver company that used Watcom commercial before it ceased to exist.

I haven't decided what compilers will be supported off-Linux.

There will be no MinGW, MSYS2 or any other such hodge-podge. I said we "might" also use it. The "might" has to do with a not insignificant segment of the market you obviously know nothing about. One is a medical device manufacturer that has some devices for the human heart and other things that are developed with OS/2. Every few years I get calls about projects for them. The other is a big ATM farm that runs OS/2. If developers from either company choose to join because their employer allows them to work on this during their day job.

As always, you can fork your own branch into your own project, changing _all_ branding and work thousands of hours for free having all kinds of people telling you to do something else.

This project is targeted at embedded systems (mostly medical devices on ARM v8) and the desktops used to create said devices. That's the realm I've worked in for the past decade. This will be the library I (and everybody else) has needed on each and every project.
